import './globals.css';
import { Ubuntu } from 'next/font/google';
import Notification from '@/components/Notification';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const inter = Ubuntu({
  subsets: ['latin'],
  weight: ["300", "400", "500", "700"]
})

export const metadata = {
  title: 'Food Ordering App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Notification />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
